INSERT INTO Product (name, desc, brand, price, category, releasedate, available, qty)
VALUES ('Smartphone X', 'A high-end smartphone with excellent performance.', 'TechBrand', 69999, 'Electronics',
        '2023-01-15', TRUE, 50),
       ('Gaming Laptop Z', 'A powerful gaming laptop with the latest GPU.', 'GamePro', 149999, 'Computers',
        '2022-11-20', TRUE, 20),
       ('Wireless Earbuds', 'Compact and lightweight earbuds with high-quality sound.', 'Soundly', 7999, 'Accessories',
        '2023-03-05', TRUE, 100),
       ('4K Smart TV', 'Ultra HD Smart TV with streaming capabilities.', 'VisionTech', 54999, 'Electronics',
        '2023-02-10', FALSE, 0),
       ('Bluetooth Speaker', 'Portable speaker with deep bass and long battery life.', 'AudioMax', 4999, 'Accessories',
        '2022-12-25', TRUE, 75),
       ('Digital Camera', 'Compact digital camera with 20MP resolution.', 'CapturePro', 45999, 'Photography',
        '2023-05-15', TRUE, 10),
       ('Smartwatch Pro', 'A smartwatch with health tracking and notifications.', 'Wristly', 15999, 'Wearables',
        '2023-04-01', TRUE, 30),
       ('Gaming Console Y', 'The ultimate gaming console for immersive experiences.', 'GameZone', 39999, 'Gaming',
        '2022-09-10', FALSE, 0),
       ('Air Purifier', 'Efficient air purifier for a cleaner and healthier home.', 'PureAir', 12999, 'Home Appliances',
        '2023-03-20', TRUE, 40),
       ('Fitness Band', 'Track your daily activities and monitor your health.', 'FitTrack', 4999, 'Wearables',
        '2023-06-10', TRUE, 60);
